services:
  app:
    build: .
    container_name: arena_server
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: arena_redis
    ports:
      - "6379:6379"