services:
  frontend:
    build: .
    container_name: arena_frontend
    command: ./frontend
    ports:
      - "50051:50051"
      - "2112:2112"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    # deploy:         # UNCOMMENT THIS TO SHOW OFF SCALING
    #   replicas: 2

  matchmaker:
    build: .
    container_name: arena_worker
    command: ./matchmaker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: arena_redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: arena_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
