# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import matchmaker_pb2 as matchmaker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in matchmaker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchmakerServiceStub(object):
    """The Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindMatch = channel.unary_unary(
                '/matchmaker.MatchmakerService/FindMatch',
                request_serializer=matchmaker__pb2.FindMatchRequest.SerializeToString,
                response_deserializer=matchmaker__pb2.FindMatchResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/matchmaker.MatchmakerService/ReportResult',
                request_serializer=matchmaker__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=matchmaker__pb2.ReportResultResponse.FromString,
                _registered_method=True)


class MatchmakerServiceServicer(object):
    """The Service definition
    """

    def FindMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchmakerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.FindMatch,
                    request_deserializer=matchmaker__pb2.FindMatchRequest.FromString,
                    response_serializer=matchmaker__pb2.FindMatchResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=matchmaker__pb2.ReportResultRequest.FromString,
                    response_serializer=matchmaker__pb2.ReportResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matchmaker.MatchmakerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('matchmaker.MatchmakerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchmakerService(object):
    """The Service definition
    """

    @staticmethod
    def FindMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matchmaker.MatchmakerService/FindMatch',
            matchmaker__pb2.FindMatchRequest.SerializeToString,
            matchmaker__pb2.FindMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/matchmaker.MatchmakerService/ReportResult',
            matchmaker__pb2.ReportResultRequest.SerializeToString,
            matchmaker__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
